name: lab2-express-js

services:
  # Container to running a node app
  node-application:
    container_name: node-application
    build:
      context: ./
      dockerfile: ./Dockerfile
    #image: cmz5478/express-js-ordering-system
    ports:
      # Map host port 7000 to container port 4500
      - "7000:4500" 
    environment:
      # Express listens on port 4500 inside the container
      CONTAINER_EXPRESS_PORT: 4500
      # Port is mapped to 7000 on the host
      HOST_EXPRESS_PORT: 7000
      # App connects to the Mongo database running in the other container at this URL
      MONGO_URL: mongodb://mongo:27017/
    restart: always

  # Container running a local MongoDB instance
  #
  # WARNING: This database has NO authentication
  # If it were exposed to the internet, then it should require a root user/password
  # However, it is running locally
  mongo:
    container_name: mongo
    volumes:
      - mongodata:/data/db
    ports:
      # Map host port 27017 (default mongo port) to same container port
      - "27017:27017"
    image: mongo:latest
    restart: always

volumes:
  mongodata:
